# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('female', '0005_auto_20161221_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchList',
            fields=[
                ('branch_id', models.TextField(db_column='branch_ID', primary_key=True, serialize=False)),
                ('region', models.TextField(blank=True, null=True)),
                ('customer_num', models.IntegerField(blank=True, null=True)),
                ('ranking', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'branch_list',
                'managed': False,
            },
        ),
    ]
