# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('female', '0007_shortage'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordCounter',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('keyword', models.TextField()),
                ('frequence', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'keyword_counter',
            },
        ),
        migrations.CreateModel(
            name='KeywordRelations',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_id', models.TextField()),
                ('product_name', models.TextField()),
                ('keyword', models.TextField()),
                ('keyword_weight', models.TextField(blank=True, null=True)),
                ('price', models.TextField(blank=True, null=True)),
                ('img_url', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'keyword_relations',
            },
        ),
    ]
