# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('female', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchRequest',
            fields=[
                ('product_id', models.IntegerField(db_column='Product_ID', primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, db_column='Name', null=True)),
                ('price', models.IntegerField(blank=True, db_column='Price', null=True)),
                ('weight', models.IntegerField(blank=True, db_column='Weight', null=True)),
                ('type', models.TextField(blank=True, db_column='Type', null=True)),
                ('productivity', models.TextField(blank=True, db_column='Productivity', null=True)),
                ('sales_quantity', models.IntegerField(blank=True, db_column='Sales_quantity', null=True)),
                ('inventory', models.IntegerField(blank=True, db_column='Inventory', null=True)),
            ],
            options={
                'db_table': 'branch_request',
                'managed': False,
            },
        ),
    ]
