# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('female', '0002_branchrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignUnderProduction',
            fields=[
                ('product_id', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('publish_date', models.TextField(blank=True, null=True)),
                ('recommend_price', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'design_under_production',
            },
        ),
    ]
