# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 16:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('female', '0003_designunderproduction'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='designunderproduction',
            table='design_under_production_)',
        ),
    ]
