# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 16:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('female', '0004_auto_20161221_1605'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='designunderproduction',
            table='design_under_production',
        ),
    ]
