# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-26 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('female', '0006_branchlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shortage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortage_id', models.IntegerField(blank=True, null=True)),
                ('branch_id', models.TextField(blank=True, null=True)),
                ('product_id', models.TextField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('has_send', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Shortage',
                'managed': False,
            },
        ),
    ]
